export const GET_TOP_MOVIES_START = "GET_TOP_MOVIES_START";
export const GET_TOP_MOVIES_SUCCESS = "GET_TOP_MOVIES_SUCCESS";
export const GET_TOP_MOVIES_FAIL = "GET_TOP_MOVIES_FAIL";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const OPEN_MOVIE_MODAL = "OPEN_MOVIE_MODAL";
export const CLOSE_MOVIE_MODAL = "CLOSE_MOVIE_MODAL";
