export const GET_TOP_MOVIES = "GET_TOP_MOVIES";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const OPEN_MOVIE_MODAL = "OPEN_MOVIE_MODAL";
export const CLOSE_MOVIE_MODAL = "CLOSE_MOVIE_MODAL";
